"""Canonical stock-sheet column names used by API models."""

CANONICAL_COLUMNS: list[str] = [
    "Unit",
    "Abu Dhabi Musaffah",
    "ALAin Mazyad",
    "AlAin Maryad (Strategic)",
    "AlAin Mazyad (Acc)",
    "Al Aln Sanaya B Block - A",
    "Al Aln Sanaya B Block - B",
    "Al Aln Sanaya B Block - C",
    "Al Aln Sanaya B Block - D",
    "Mazyad (6 months contr)",
    "DIC1",
    "DIC2",
    "DIC3",
    "DIC4",
    "DIC5",
    "DIC6",
    "DIC7",
    "DIC8",
    "DIC9",
    "DIC9 (Strategic)",
    "DIC10",
    "DIC11",
    "Sharja Sajaa Block B",
    "Sharja Sajaa Block C",
    "Total Bags",
]
